### ISSUE TITLE
Artnet_DMX_SD_Card

### ISSUE THREAD

**Issue by mzhajjar** [tangophi/Artnet_DMX_SD_Card#1]
Can i use them with 50 synchronize universes

**Comment by tangophi** [comment]
Should be okay.   Only the speed of the ESP8266 and how fast it can write to the SD card determines how many universes you can use.  Guess its a trial and error method to find that number.

**Comment by DonMacarena** [comment]
Hello ! 
How can I use the recording on the SD card to play DMX 512? What needs to be changed in the code? Help please, really want to make a standalone player for my Led PAR

**Comment by tangophi** [comment]
I guess DMX is actually DMX512.  Hence the sketches should work as they are.

**Comment by DonMacarena** [comment]
Output format  for WS2812 is NOT the same as for DMX 512 


>Среда,  7 марта 2018, 15:08 +02:00 от tangophi <notifications@github.com>:
>
>I guess DMX is actually DMX512.  Hence the sketches should work as they are.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Diana A

**Comment by tangophi** [comment]
What was the problem you saw when you used my sketch?  Can you please explain.
