### ISSUE TITLE
unable to upload to arduino

### ISSUE THREAD

**Issue by wizzgit** [tangophi/Artnet_DMX_SD_Card#4]
sorry i'm really noob in coding
i try to upload this sketch to my arduino uno
but i have error

D:/Arduino/NEOPIXEL/Projet Echasse PlatformIO/PROJECT MADRIX/src/Store_DMX_Frames_Received_Through_ArtNet_To_SD_Card TEST.ino:205:66: error: no matching function for call to 'HardwareSerial::print(const char [30], uint16_t&, uint16_t&)'
   Serial.print("DMX recd: univ=%3d : len=%3d\n", universe, length);

i dont understand what happend.
Can you help me

**Comment by tangophi** [comment]
This sketch is meant for a ESP8266 chipset.  I am not sure how you can use it on a Arduino Uno as it has no WiFi connectivity.
